podcast/urls.py
from __future__ import unicode_literals

try:
    from django.urls import include, re_path
except ImportError:
    from django.conf.urls import include, url as re_path

from .views import EpisodeDetailView, EpisodeDownloadView, ShowDetailView, ShowFeedView, ShowListView
from . import settings


app_name = 'podcast'

singular = [
    re_path(r'^feed/$', ShowFeedView.as_view(), name='show_feed'),
    re_path(r'^(?P<slug>[\w-]+)/download/$', EpisodeDownloadView.as_view(), name='episode_download'),
    re_path(r'^(?P<slug>[\w-]+)/$', EpisodeDetailView.as_view(), name='episode_detail'),
    re_path(r'^$', ShowDetailView.as_view(), name='show_detail'),
]

if settings.PODCAST_SINGULAR:
    urlpatterns = singular
else:
    urlpatterns = [
        re_path(r'^(?P<show_slug>[\w-]+)/', include(singular)),
        re_path(r'^$', ShowListView.as_view(), name='show_list'),
    ]

podcast/models.py
from __future__ import division
from __future__ import unicode_literals

import hashlib
from ast import literal_eval
from datetime import timedelta

from django.contrib.staticfiles.storage import staticfiles_storage
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone
from django.utils.encoding import force_bytes, python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

import bleach
import mutagen

from .managers import EpisodeManager
from .utils import enclosure_file_path, enclosure_poster_path, episode_image_path, show_image_path, speaker_photo_path
from . import settings

try:
    from django.urls import reverse
except ImportError:
    from django.core.urlresolvers import reverse


@python_2_unicode_compatible
class Speaker(models.Model):
    name = models.CharField(_("Name"), max_length=255)
    email = models.EmailField(_("E-mail"), unique=True)
    photo = models.ImageField(_("Photo"), upload_to=speaker_photo_path, blank=True)
    bio = models.TextField(_("Bio"), blank=True)

    class Meta:
        ordering = ["name", "email"]
        verbose_name = _("speaker")
        verbose_name_plural = _("speakers")

    def __str__(self):
        return "%s" % self.name


@python_2_unicode_compatible
class Category(models.Model):
    parent = models.ForeignKey("self", verbose_name=_("parent"), related_name=_("children"), null=True, blank=True, on_delete=models.CASCADE)
    title = models.CharField(_("title"), max_length=255)
    slug = models.SlugField(_("slug"), unique=True)
    full = models.CharField(_("full title"), max_length=255, editable=False)

    class Meta:
        ordering = ["full"]
        verbose_name = _("category")
        verbose_name_plural = _("categories")

    def __str__(self):
        return "%s" % self.get_str(self)

    def save(self, *args, **kwargs):
        self.full = self.get_str(self)
        super(Category, self).save(*args, **kwargs)

    def get_str(self, obj, delimiter=" | ", trail=""):
        delimiter = delimiter if trail else ""
        if obj.parent:
            return self.get_str(obj.parent, trail="%s%s%s" % (obj.title, delimiter, trail))
        else:
            return "%s%s%s" % (obj.title, delimiter, trail)


@python_2_unicode_compatible
class Show(models.Model):
    TYPE_CHOICES = (
        ("episodic", _("Episodic")),
        ("serial", _("Serial")),
    )
    type = models.CharField(_("type"), max_length=255, choices=TYPE_CHOICES, default="episodic", help_text=_("Episodic presents episodes by latest, serial presents episodes by episode number; both support seasons"))
    title = models.CharField(_("title"), max_length=255)
    slug = models.SlugField(_("slug"), unique=True)
    image = models.ImageField(_("image"), upload_to=show_image_path, blank=True, help_text=_("1400&times;1400&ndash;3000&times;3000px; 72DPI; JPG, PNG; RGB; if blank, default <a href=\"%s\">no artwork</a> is used") % staticfiles_storage.url(settings.PODCAST_NO_ARTWORK))
    description = models.TextField(_("description"), help_text=_("Accepts HTML"))
    managing_editor = models.EmailField(_("editor e-mail"), max_length=255, default="", help_text=_("E-mail of administrative contact"))
    webmaster = models.EmailField(_("webmaster e-mail"), max_length=255, blank=True, help_text=_("E-mail of technical contact; if blank, uses editor e-mail"))
    ttl = models.PositiveIntegerField(_("TTL"), default=60, help_text=_("Time to live; minutes until cached feed refreshed"))
    subtitle = models.CharField(_("subtitle"), max_length=255, help_text=_("A single, descriptive sentence of the show"))
    summary = models.TextField(_("summary"), blank=True, max_length=4000, help_text=_("Max length of 4,000 characters; accepts HTML; if blank, uses show's description"))
    author_name = models.CharField(_("author name"), max_length=255, blank=True, help_text=_("Name of \"artist\" of the podcast; if blank, uses show title"))
    author_email = models.EmailField(_("author e-mail"), blank=True, help_text=_("E-mail of administrative contact; if blank, uses editor e-mail"))
    owner_name = models.CharField(_("owner name"), max_length=255, blank=True, help_text=_("Name of technical contact; if blank, uses show title"))
    owner_email = models.EmailField(_("owner e-mail"), blank=True, help_text=_("E-mail of technical contact; if blank, uses webmaster e-mail"))
    copyright = models.CharField(_("copyright"), max_length=255, blank=True, help_text=_("Organization name; &copy; and %s will be prepended automatically; if blank, uses show's title" % timezone.now().year))
    categories = models.ManyToManyField(Category, verbose_name=_("categories"), help_text=_("Please select parent category if selecting a subcategory, e.g. <strong>Arts</strong> if <strong>Arts / Design</strong>"))
    explicit = models.BooleanField(_("explicit?"), default=False, help_text=_("Indicates explicit language or adult content"))
    block = models.BooleanField(_("block?"), default=False, help_text=_("Prevents entire podcast from appearing on Apple Podcasts"))
    complete = models.BooleanField(_("complete?"), default=False, help_text=_("Indicates entire podcast is complete and no future episodes will be created"))
    apple = models.URLField(_("Apple Podcasts URL"), blank=True, help_text=_("Paste Apple Podcasts URL here after submission of show feed URL to <a href=\"https://podcastsconnect.apple.com/\">Podcasts Connect</a>"))
    coming = models.BooleanField(_("coming"), default=False, help_text=_("Indicates whether users are coming from an old feed; if set, leave for four weeks; see <a href=\"https://help.apple.com/itc/podcasts_connect/#/itca489031e0\">documentation</a>"))
    going = models.URLField(_("going"), blank=True, help_text=_("Permanently redirect users to URL of a new feed; see <a href=\"https://help.apple.com/itc/podcasts_connect/#/itca489031e0\">documentation</a>"))
    hosts = models.ManyToManyField(Speaker, verbose_name=_("hosts"), blank=True)

    class Meta:
        ordering = ["title"]
        verbose_name = _("show")
        verbose_name_plural = _("shows")

    def __str__(self):
        return "%s" % self.title

    def get_absolute_url(self):
        if settings.PODCAST_SINGULAR:
            return reverse("podcast:show_detail")
        else:
            return reverse("podcast:show_detail", args=[self.slug])

    def get_absolute_feed_url(self):
        if settings.PODCAST_SINGULAR:
            return reverse("podcast:show_feed")
        else:
            return reverse("podcast:show_feed", args=[self.slug])

    def get_image_url(self):
        return self.image.url if self.image else staticfiles_storage.url(settings.PODCAST_NO_ARTWORK)

    def get_ttl(self):
        return str(self.ttl) if self.ttl else ""

    def get_subtitle(self):
        text = self.subtitle
        tags = []
        return bleach.clean(text, tags=tags, strip=True)

    def get_summary(self):
        text = self.summary if self.summary else self.description
        tags = settings.PODCAST_ALLOWED_TAGS
        return bleach.clean(text, tags=tags, strip=True)

    def get_webmaster(self):
        return self.webmaster if self.webmaster else self.managing_editor

    def get_author_name(self):
        return self.author_name if self.author_name else self.title

    def get_author_email(self):
        return self.author_email if self.author_email else self.managing_editor

    def get_owner_name(self):
        return self.owner_name if self.owner_name else self.title

    def get_owner_email(self):
        return self.owner_email if self.owner_email else self.get_webmaster()

    def get_category(self, obj, trail={}):
        if obj.parent:
            return self.get_category(obj.parent, trail={obj.title: trail})
        else:
            return {obj.title: trail}

    def get_categories(self):
        # Apple Podcasts-friendly categories; i.e. not recursive
        # e.g.: {'Arts': ['Food'], 'TV & Film': [], 'Technology': ['Gadgets']}
        categories = {}
        for item in [self.get_category(obj) for obj in self.categories.all()]:
            for key in item:
                if not key in categories:
                    categories[key] = []
                else:
                    for k in item[key]:
                        categories[key].append(k)
        return categories

    def get_explicit(self):
        return "yes" if self.explicit else "no"

    def get_block(self):
        return "yes" if self.block else "no"

    def get_complete(self):
        return "yes" if self.complete else "no"

    def get_latest_duration(self):
        episode = self.episode_set.all().first()
        return episode.enclosure.get_duration() if episode else ""
    get_latest_duration.short_description = _("last episode duration")

    def get_latest_pub_date(self):
        episode = self.episode_set.all().first()
        return episode.pub_date if episode else ""
    get_latest_pub_date.short_description = _("last episode pub date")


@python_2_unicode_compatible
class Episode(models.Model):
    STATUS_CHOICES = (
        ("public", _("Public")),
        ("secret", _("Secret")),
        ("private", _("Private")),
    )
    TYPE_CHOICES = (
        ("full", _("Full")),
        ("trailer", _("Trailer")),
        ("bonus", _("Bonus")),
    )
    show = models.ForeignKey(Show, verbose_name=_("show"), on_delete=models.CASCADE)
    title = models.CharField(_("title"), max_length=255)
    slug = models.SlugField(_("slug"),)
    description = models.TextField(_("description"), help_text=_("Accepts HTML"))
    pub_date = models.DateTimeField(_("pub date"), help_text=_("If in future, episode hidden until date arrives (unless status is secret)"))
    status = models.CharField(_("status"), max_length=255, choices=STATUS_CHOICES, default="public", help_text=_("Public is openly visible; secret is visibile but unlisted; private is not visible"))

podcast/templates/podcast/episode_detail.html
{% extends "base.html" %}

{% load i18n staticfiles podcast_tags %}


{% block title %}{{ episode.title }} &#183; {{ block.super }}{% endblock %}


{% block feed %}
<link rel="alternate" type="application/rss+xml" href="{{ episode.show.get_absolute_feed_url }}" title="{{ episode.show.title }}">
{% endblock %}

{% block extra_head %}
<meta property="og:title" content="{{ episode.title }}">
{% if episode.enclosure %}
{% with enclosure=episode.enclosure %}
    <meta property="og:type" content="{% if enclosure.is_audio %}music.song{% elif enclosure.is_video %}video.other{% endif %}">
    <meta property="og:image" content="{{ enclosure.get_poster_url }}">
    <meta property="og:url" content="{{ request.build_absolute_uri }}">
    <meta property="og:description" content="{{ episode.description|striptags }}">
    <meta property="og:{% if enclosure.is_audio %}audio{% elif enclosure.is_video %}video{% endif %}" content="http{% if request.is_secure %}s{% endif %}://{{ request.get_host }}{{ episode.get_absolute_download_url }}">
    <meta property="og:{% if enclosure.is_audio %}audio{% elif enclosure.is_video %}video{% endif %}:type" content="{{ enclosure.type }}">
{% endwith %}
{% endif %}
{% if episode.is_secret %}
<meta name="robots" content="noindex, nofollow, noarchive, nosnippet">
{% endif %}
{% endblock %}


{% block content %}

{% get_podcast_singular as podcast_singular %}

<ul>
    {% if not podcast_singular %}
    <li><a href="{% url 'podcast:show_list' %}">{% trans 'Podcasts' %}</a></li>
    {% endif %}
    <li><a href="{{ episode.show.get_absolute_url }}">{{ episode.show.title }}</a></li>
</ul>

<h1>{{ episode.title }}</h1>

<p>{% trans 'Episode' %} {{ episode.index }}</p>

<p><time datetime="{{ episode.pub_date|date:'c' }}" title="{{ episode.pub_date|date:'c' }}">{{ episode.pub_date|date:'j F Y' }}</time></p>

{% if episode.description %}
<p>{{ episode.description|safe }}</p>
{% endif %}

{% if episode.enclosure %}
{% with enclosure=episode.enclosure %}

    {# Audio #}
    {% if enclosure.is_audio %}
    <audio src="{{ episode.get_absolute_download_url }}" controls>
        <p><a href="{{ episode.get_absolute_download_url }}">{% trans 'Download the audio' %}</a>.</p>
    </audio>
    <p>{{ enclosure.get_duration }}</p>

    {# Video #}
    {% elif enclosure.is_video %}
    <video poster="{{ enclosure.get_poster_url }}" controls>
        <source src="{{ episode.get_absolute_download_url }}" type="{{ enclosure.type }}">
        <p><a href="{{ episode.get_absolute_download_url }}">{% trans 'Download the video' %}</a>.</p>
    </video>
    <p>{{ enclosure.get_duration }}</p>    
    {% endif %}

    <p><a href="{{ episode.get_absolute_download_url }}">{% trans 'Download the' %} {{ enclosure.get_megabytes }} {% trans 'MB' %} {{ enclosure.get_type_display }}</a>.</p>

{% endwith %}
{% endif %}

{% if episode.show.apple %}<p><a href="{{ episode.show.apple }}"><img src="{% static 'podcast/img/badge.svg' %}" alt="{% trans 'Listen on Apple Podcasts' %}"></a></p>{% endif %}
<p><a href="{{ episode.show.get_absolute_feed_url }}" title="Really Simple Syndication">{% trans 'Subscribe to RSS' %}</a></p>

{% if episode.get_previous or episode.get_next %}
<ul>
    {% if episode.get_next %}
    <li><a href="{{ episode.get_next.get_absolute_url }}">&larr; {% trans 'Episode' %} {{ episode.index_next }}: {{ episode.get_next.title }}</a></li>
    {% endif %}
    {% if episode.get_previous %}
    <li><a href="{{ episode.get_previous.get_absolute_url }}">{% trans 'Episode' %} {{ episode.index_previous }}: {{ episode.get_previous.title }} &rarr;</a></li>
    {% endif %}
</ul>
{% endif %}

{% endblock %}

podcast/templates/podcast/pagination.html
{% load i18n %}

{% if page_obj.has_other_pages %}
<ul>
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}">&larr; {% trans 'Previous' %}</a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}">{% trans 'Next' %} &rarr;</a></li>
    {% endif %}
</ul>
{% endif %}

podcast/templates/podcast/show_detail.html
{% extends "base.html" %}

{% load i18n staticfiles podcast_tags %}


{% block title %}{{ show.title }} &#183; {{ block.super }}{% endblock %}


{% block feed %}
<link rel="alternate" type="application/rss+xml" href="{{ show.get_absolute_feed_url }}" title="{{ show.title }}">
{% endblock %}


{% block content %}

{% get_podcast_singular as podcast_singular %}

{% if not podcast_singular %}
    <ul>
        <li><a href="{% url 'podcast:show_list' %}">{% trans 'Podcasts' %}</a></li>
    </ul>
{% endif %}

<h1>{{ show.title }}</h1>

<p><a href="{{ show.get_image_url }}"><img src="{{ show.get_image_url }}" alt="{{ show.title }} artwork" width="300"></a></p>

{% if show.description %}
<p>{{ show.description }}</p>
{% endif %}

{% if show.apple %}<p><a href="{{ show.apple }}"><img src="{% static 'podcast/img/badge.svg' %}" alt="{% trans 'Listen on Apple Podcasts' %}"></a></p>{% endif %}
<p><a href="{{ show.get_absolute_feed_url }}" title="Really Simple Syndication">{% trans 'Subscribe to RSS' %}</a></p>

{% if episode_list %}

    <h2>{% trans 'Episodes' %}</h2>

    {% blocktrans count episode_count=page_obj.paginator.count %}
    <p>{{ episode_count }} episode</p>
    {% plural %}
    <p>{{ episode_count }} episodes</p>
    {% endblocktrans %}

    {% for episode in episode_list %}
        <h3><a href="{{ episode.get_absolute_url }}">{{ episode.title }}</a></h3>
        <p>{% trans 'Episode' %} {{ episode.index }}</p>
        <p><time datetime="{{ episode.pub_date|date:'c' }}" title="{{ episode.pub_date|date:'c' }}">{{ episode.pub_date|date:'j F Y' }}</time></p>
        {% if episode.description %}
        <p>{{ episode.description|safe }}</p>
        {% endif %}
    {% endfor %}

    {% include 'podcast/pagination.html' %}

{% endif %}

{% endblock %}

podcast/templates/podcast/show_list.html
{% extends "base.html" %}

{% load i18n %}


{% block title %}{% trans 'Podcasts' %} &#183; {{ block.super }}{% endblock %}


{% block content %}

<h1>{% trans 'Podcasts' %}</h1>

{% blocktrans count show_count=page_obj.paginator.count %}
<p>{{ show_count }} show</p>
{% plural %}
<p>{{ show_count }} shows</p>
{% endblocktrans %}

{% if show_list %}

    {% for show in show_list %}
        <h2><a href="{{ show.get_absolute_url }}">{{ show.title }}</a></h2>
        <div>
            <a href="{{ show.get_absolute_url }}"><img src="{{ show.get_image_url }}" alt="{{ show.title }} artwork" width="300"></a>
        </div>
        {% if show.description %}
        <p>{{ show.description|safe }}</p>
        {% endif %}
    {% endfor %}

    {% include 'podcast/pagination.html' %}

{% endif %}

{% endblock %}